---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  Remote access role for Duckbill Group.

Parameters:
  CustomerNameSlug:
    Type: String
    Description: >
      A short, lower-case slug that identifies your company, e.g. acme-corp
      Duckbill Group will need to know this value, so that we can set up our own
      infrastructure for you.
    AllowedPattern: ^[a-z0-9-]*$
  CURBucketName:
    Type: String
    Description: >
      Name of the S3 bucket in which you are storing Cost and Usage Reports.
    AllowedPattern: ^[a-z0-9-\.]*$
    MinLength: 3
    MaxLength: 63
  ExternalID:
    Type: String
    Description: >
      The External ID provided to you by Duckbill Cloud Economist

Resources:
  DuckbillGroupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: DuckbillGroupRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Principal:
              AWS: 753095100886
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: ExternalID
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/job-function/Billing
        - arn:aws:iam::aws:policy/AWSSavingsPlansReadOnlyAccess
        - !Ref DuckbillGroupBillingPolicy
        - !Ref DuckbillGroupResourceDiscoveryPolicy
        - !Ref DuckbillGroupCURIngestPipelinePolicy
        - !Ref DuckbillGroupDenySensitiveAccessPolicy

  DuckbillGroupBillingPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: DuckbillGroupBilling
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'ce:*'
              - 'cur:DescribeReportDefinitions'
              - 'aws-portal:ViewBilling'
              - 'aws-portal:ViewUsage'
              - 'budgets:ViewBudget'
              - 'compute-optimizer:Get*'
              - 'glue:BatchGetJobs'
              - 'glue:ListJobs'
              - 'pricing:GetProducts'
            Effect: Allow
            Resource: '*'

  DuckbillGroupResourceDiscoveryPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: DuckbillGroupResourceDiscovery
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'acm:Describe*'
              - 'apigateway:GET'
              - 'batch:Describe*'
              - 'cloudhsm:Describe*'
              - 'cloudhsm:List*'
              - 'cloudwatch:Describe*'
              - 'codebuild:BatchGetProjects'
              - 'codecommit:BatchGetRepositories'
              - 'cognito-identity:Describe*'
              - 'cognito-idp:Describe*'
              - 'dax:Describe*'
              - 'dlm:Get*'
              - 'dms:Describe*'
              - 'ec2:Describe*'
              - 'eks:Describe*'
              - 'eks:List*'
              - 'elasticfilesystem:Describe*'
              - 'elasticbeanstalk:ListTagsForResource'
              - 'elasticmapreduce:Describe*'
              - 'es:ListTags'
              - 'es:DescribeReservedElasticsearchInstances'
              - 'fsx:Describe*'
              - 'glue:Get*'
              - 'glue:List*'
              - 'health:Describe*'
              - 'iam:GetPolicyVersion'
              - 'iam:GetRole'
              - 'iam:GetUser'
              - 'kafka:List*'
              - 'kinesis:Describe*'
              - 'kinesis:List*'
              - 'kms:Describe*'
              - 'kms:List*'
              - 'lambda:Get*'
              - 'lambda:List*'
              - 'lightsail:GetInstances'
              - 'lightsail:GetLoadBalancers'
              - 'lightsail:GetRelationalDatabases'
              - 'macie2:Describe*'
              - 'macie2:ListTagsForResources'
              - 'macie2:GetBucketStatistics'
              - 'macie2:GetMacieSession'
              - 'macie2:GetUsageStatistics'
              - 'macie2:GetUsageTotals'
              - 'medialive:Describe*'
              - 'medialive:list*'
              - 'mq:List*'
              - 'redshift:Describe*'
              - 's3:GetAnalyticsConfiguration'
              - 's3:GetBucket*'
              - 's3:GetReplication*'
              - 's3:GetStorageLensDashboard'
              - 's3:GetStorageLensConfiguration'
              - 's3:ListStorageLensConfigurations'
              - 'secretsmanager:ListSecrets'
              - 'shield:List*'
              - 'snowball:List*'
              - 'sns:GetTopicAttributes'
              - 'ssm:Describe*'
              - 'tag:Get*'
            Effect: Allow
            Resource: '*'

  DuckbillGroupCURIngestPipelinePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: DuckbillGroupCURIngestPipeline
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:ListBucket'
              - 's3:GetObject'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::${CURBucketName}'
              - !Sub 'arn:aws:s3:::${CURBucketName}/*'
          - Action:
              - 's3:ListBucket'
              - 's3:PutObject'
              - 's3:PutObjectAcl'
            Effect: Allow
            Resource:
              - !Sub 'arn:aws:s3:::dbg-cur-ingest-${CustomerNameSlug}'
              - !Sub 'arn:aws:s3:::dbg-cur-ingest-${CustomerNameSlug}/*'
              - !Sub
                - 'arn:aws:s3:::dbg-cur-ingest-${external_id_prefix}'
                - external_id_prefix: !Select [0, !Split ['-', !Sub '${ExternalID}']]
              - !Sub
                - 'arn:aws:s3:::dbg-cur-ingest-${external_id_prefix}/*'
                - external_id_prefix: !Select [0, !Split ['-', !Sub '${ExternalID}']]


  DuckbillGroupDenySensitiveAccessPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: DuckbillGroupDenySensitiveAccess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Deny
            Action:
              - aoss:APIAccessAll
              - aoss:DashboardsAccessAll
              - appsync:GetDataSource
              - appsync:GetFunction
              - athena:GetQueryExecution
              - athena:GetQueryResults
              - athena:GetQueryResultsStream
              - cassandra:Select
              - chatbot:DescribeSlackChannels
              - chatbot:DescribeSlackUserIdentities
              - chatbot:ListMicrosoftTeamsConfiguredTeams
              - chatbot:ListMicrosoftTeamsUserIdentities
              - chime:GetAttendee
              - chime:GetChannelMessage
              - chime:GetMeeting
              - chime:GetMeetingDetail
              - chime:GetRoom
              - chime:GetUser
              - chime:GetUserActivityReportData
              - chime:GetUserByEmail
              - chime:GetUserSettings
              - chime:ListAttendees
              - chime:ListMeetingEvents
              - chime:ListMeetings
              - chime:ListUsers
              - cleanrooms:GetProtectedQuery
              - cloudformation:GetTemplate
              - cloudfront:GetFunction
              - cloudtrail:GetQueryResults
              - cloudtrail:LookupEvents
              - codeartifact:GetPackageVersionAsset
              - codeartifact:GetPackageVersionReadme
              - codeartifact:ReadFromRepository
              - codebuild:BatchGetReportGroups
              - codebuild:BatchGetReports
              - codecommit:BatchGetCommits
              - codecommit:BatchGetPullRequests
              - codecommit:BatchGetRepositories
              - codecommit:DescribeMergeConflicts
              - codecommit:DescribePullRequestEvents
              - codecommit:GetApprovalRuleTemplate
              - codecommit:GetBlob
              - codecommit:GetBranch
              - codecommit:GetComment
              - codecommit:GetCommentReactions
              - codecommit:GetCommentsForComparedCommit
              - codecommit:GetCommentsForPullRequest
              - codecommit:GetCommit
              - codecommit:GetCommitHistory
              - codecommit:GetCommitsFromMergeBase
              - codecommit:GetDifferences
              - codecommit:GetFile
              - codecommit:GetFolder
              - codecommit:GetMergeCommit
              - codecommit:GetMergeConflicts
              - codecommit:GetMergeOptions
              - codecommit:GetObjectIdentifier
              - codecommit:GetPullRequest
              - codecommit:GetPullRequestApprovalStates
              - codecommit:GetPullRequestOverrideState
              - codecommit:GetReferences
              - codecommit:GetTree
              - codecommit:GitPull
              - codeguru-profiler:GetRecommendations
              - codeguru-reviewer:DescribeCodeReview
              - codeguru-reviewer:DescribeRecommendationFeedback
              - codepipeline:GetPipelineExecution
              - cognito-identity:LookupDeveloperIdentity
              - cognito-idp:AdminGetDevice
              - cognito-idp:AdminGetUser
              - cognito-idp:AdminListDevices
              - cognito-idp:AdminListGroupsForUser
              - cognito-idp:AdminListUserAuthEvents
              - cognito-idp:GetDevice
              - cognito-idp:GetGroup
              - cognito-idp:GetUser
              - cognito-idp:ListUsers
              - cognito-idp:ListDevices
              - cognito-idp:ListGroups
              - cognito-sync:ListRecords
              - cognito-sync:QueryRecords
              - connect:ListUsers
              - datapipeline:QueryObjects
              - dax:BatchGetItem
              - dax:GetItem
              - dax:Query
              - dax:Scan
              - dynamodb:BatchGetItem
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:Query
              - dynamodb:Scan
              - ecr:GetDownloadUrlForLayer
              - es:ESHttpDelete
              - es:ESHttpGet
              - es:ESHttpHead
              - es:ESHttpPatch
              - es:ESHttpPost
              - es:ESHttpPut
              - gamelift:GetInstanceAccess
              - healthlake:ReadResource
              - healthlake:SearchWithGet
              - healthlake:SearchWithPost
              - kendra:Query
              - kinesis:GetRecords
              - kinesisvideo:GetImages
              - kinesisvideo:GetMedia
              - lambda:GetFunction
              - lambda:GetLayerVersion
              - lightsail:GetContainerImages
              - logs:GetLogEvents
              - logs:GetLogRecord
              - logs:GetQueryResults
              - macie2:GetFindings
              - mediastore:GetObject
              - qldb:GetBlock
              - rds:DownloadCompleteDBLogFile
              - rds:DownloadDBLogFilePortion
              - robomaker:GetWorldTemplateBody
              - s3-object-lambda:GetObject
              - s3-object-lambda:GetObjectVersion
              - s3-object-lambda:ListBucket
              - s3:GetObject
              - s3:GetObjectVersion
              - sagemaker:Search
              - sdb:Select
              - serverlessrepo:GetApplication
              - serverlessrepo:GetCloudFormationTemplate
              - sqs:ReceiveMessage
              - ssm:GetDocument
              - ssm:GetParameter
              - ssm:GetParameterHistory
              - ssm:GetParameters
              - ssm:GetParametersByPath
              - sso-directory:DescribeGroup
              - sso-directory:DescribeUser
              - sso-directory:SearchGroups
              - sso-directory:SearchUsers
              - sso:SearchGroups
              - sso:SearchUsers
              - support:DescribeAttachment
              - support:DescribeCommunications
              - workdocs:GetDocument
              - workdocs:GetDocumentPath
              - workdocs:GetDocumentVersion
              - workmail:ListGroupMembers
              - workmail:ListGroups
              - workmail:ListUsers
            NotResource:
              - !Sub 'arn:aws:s3:::${CURBucketName}'
              - !Sub 'arn:aws:s3:::${CURBucketName}/*'
              - !Sub 'arn:aws:s3:::dbg-cur-ingest-${CustomerNameSlug}'
              - !Sub 'arn:aws:s3:::dbg-cur-ingest-${CustomerNameSlug}/*'
              - !Sub
                - 'arn:aws:s3:::dbg-cur-ingest-${external_id_prefix}'
                - external_id_prefix: !Select [0, !Split ['-', !Sub '${ExternalID}']]
              - !Sub
                - 'arn:aws:s3:::dbg-cur-ingest-${external_id_prefix}/*'
                - external_id_prefix: !Select [0, !Split ['-', !Sub '${ExternalID}']]



