AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Resources:
    DuckbillGroupRole:
        Type: "AWS::IAM::Role"
        Properties:
            RoleName: "DuckbillGroupRole"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action: "sts:AssumeRole"
                    Principal:
                        AWS: "789736909639"
                    Condition:
                        StringEquals:
                            sts:ExternalId: "PlatypusBills"
            ManagedPolicyArns:
                - !Ref DuckbillGroupBilling
                - arn:aws:iam::aws:policy/ReadOnlyAccess
                - arn:aws:iam::aws:policy/job-function/Billing

    DuckbillGroupBilling:
        Type: "AWS::IAM::ManagedPolicy"
        Properties:
            ManagedPolicyName: "DuckbillGroupBilling"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Action:
                      - "ce:*"
                      - "aws-portal:ViewBilling"
                      - "aws-portal:ViewUsage"
                      - "budgets:ViewBudget"
                      - "compute-optimizer:Get*"
                      - "glue:BatchGetJobs"
                      - "glue:ListJobs"
                      - "pricing:GetProducts"
                    Effect: "Allow"
                    Resource: "*"
