name: PR Checks
on: pull_request
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Shellcheck
        run: shellcheck *.sh
      - name: Lint IAM policy documents
        run: find ${{ github.workspace }} \( -depth 1 -type f -iname "*.json" -o -depth 1 -type f -iname "*.json.template" \) -exec jq -c . {} +
