name: PR Checks
on: pull_request
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      # Python, terraform 0.12 and shellcheck are already installed in the Ubuntu 18.04 runner
      # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md
      - name: Install dependencies
        run: pip install cfn-lint
      - name: Lint AWS-CLI scripts
        run: cd aws-cli && make lint
      - name: Lint CloudFormation YAML
        run: cd cloudformation && make lint
      - name: Lint Terraform
        run: cd terraform && make lint
