name: PR Checks
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Shellcheck
        run: shellcheck ${{ github.workspace }}/*.sh
      - name: Lint IAM policy documents
        run: |
          set -e
          for f in $(find . -maxdepth 1 \( -name '*.json' -o -name '*.json.template' \))
          do
            echo "Checking JSON for $f"
            jq -reM . $f 1>/dev/null || exit 1
          done
